USE [OdyClerkInternal]
GO

/****** Object:  Table [dbo].[TrafficCitation_Import]    Script Date: 8/11/2020 11:58:27 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TrafficCitation_Import](
	[UpdateType] [varchar](50) NULL,
	[CitationNumber] [varchar](50) NOT NULL,
	[CheckDigit] [varchar](50) NULL,
	[CountyNumber] [varchar](50) NULL,
	[JurisdictionNumber] [varchar](50) NULL,
	[CityName] [varchar](50) NULL,
	[IssueAgencyType] [varchar](50) NULL,
	[IssueAgencyCode] [varchar](50) NULL,
	[IssueAgencyName] [varchar](50) NULL,
	[DayofWeek] [varchar](100) NULL,
	[OffenseDate] [varchar](50) NULL,
	[OffenseTime] [varchar](50) NULL,
	[OffenseTimeAMPM] [varchar](50) NULL,
	[DriverFirstName] [varchar](100) NULL,
	[DriverMiddleName] [varchar](100) NULL,
	[DriverLastName] [varchar](100) NULL,
	[DriverSuffix] [varchar](50) NULL,
	[StreetAddress] [varchar](50) NULL,
	[AddressDiffLicense] [varchar](50) NULL,
	[City] [varchar](50) NULL,
	[StateofDriversAddress] [varchar](50) NULL,
	[ZipCode] [varchar](50) NULL,
	[Telephone] [varchar](50) NULL,
	[BirthDate] [varchar](50) NULL,
	[Race] [varchar](50) NULL,
	[Sex] [varchar](50) NULL,
	[Height] [varchar](50) NULL,
	[DriverLicenseNumber] [varchar](50) NULL,
	[DriverLicenseState] [varchar](50) NULL,
	[DriverLicenseClass] [varchar](50) NULL,
	[ViolationExpiredDL] [varchar](50) NULL,
	[CommercialVehicleCode] [varchar](50) NULL,
	[VehicleYear] [varchar](50) NULL,
	[VehicleMake] [varchar](50) NULL,
	[VehicleStyle] [varchar](50) NULL,
	[VehiclyColor] [varchar](50) NULL,
	[HazardousMaterials] [varchar](50) NULL,
	[VehicleTagNumber] [varchar](50) NULL,
	[VehicleTrailerNumber] [varchar](50) NULL,
	[VehicleState] [varchar](50) NULL,
	[VehicleTagExpYear] [varchar](50) NULL,
	[CompanionCitation] [varchar](50) NULL,
	[ViolationLocation] [varchar](50) NULL,
	[DistanceFeet] [varchar](50) NULL,
	[DistanceMiles] [varchar](50) NULL,
	[DirectionN] [varchar](50) NULL,
	[DirectionS] [varchar](50) NULL,
	[DirectionE] [varchar](50) NULL,
	[DirectionW] [varchar](50) NULL,
	[OfNode] [varchar](50) NULL,
	[ActualSpeed] [varchar](50) NULL,
	[PostedSpeed] [varchar](50) NULL,
	[Hwy4Lane] [varchar](50) NULL,
	[HwyInterstate] [varchar](50) NULL,
	[ViolationCareless] [varchar](50) NULL,
	[ViolationDevice] [varchar](50) NULL,
	[ViolationRow] [varchar](50) NULL,
	[ViolationLane] [varchar](50) NULL,
	[ViolationPassing] [varchar](50) NULL,
	[ViolationChildRestraint] [varchar](50) NULL,
	[ViolationDUI] [varchar](50) NULL,
	[BloodAlcoholLevel] [varchar](50) NULL,
	[ViolationSeatBelt] [varchar](50) NULL,
	[ViolationEquipment] [varchar](50) NULL,
	[ViolationTagLess] [varchar](50) NULL,
	[ViolationTagMore] [varchar](50) NULL,
	[ViolationInsurance] [varchar](50) NULL,
	[ViolationExpiredDriverLicense] [varchar](50) NULL,
	[ViolationExpiredDLMore] [varchar](50) NULL,
	[ViolationNoDL] [varchar](50) NULL,
	[ViolationSuspendedDL] [varchar](50) NULL,
	[OtherComments] [varchar](100) NULL,
	[ViolationCode] [varchar](50) NULL,
	[FLDLEditOverride] [varchar](50) NULL,
	[StateStatuteIndicator] [varchar](50) NULL,
	[Section] [varchar](50) NULL,
	[SubSection] [varchar](50) NULL,
	[Crash] [varchar](50) NULL,
	[PropertyDamage] [varchar](50) NULL,
	[PropertyDamageAmount] [varchar](50) NULL,
	[Injury] [varchar](50) NULL,
	[SeriousInjury] [varchar](50) NULL,
	[FatalInjury] [varchar](50) NULL,
	[MethodOfArrest] [varchar](50) NULL,
	[CriminalCourtReq] [varchar](50) NULL,
	[InfractionCourtReq] [varchar](50) NULL,
	[InfractionNoCourtReq] [varchar](50) NULL,
	[CourtDate] [varchar](50) NULL,
	[CourtTime] [varchar](50) NULL,
	[CourtName] [varchar](50) NULL,
	[CourtTimeAMPM] [varchar](50) NULL,
	[CourtAddress] [varchar](100) NULL,
	[CourtCity] [varchar](50) NULL,
	[CourtState] [varchar](50) NULL,
	[CourtZip] [varchar](50) NULL,
	[ArrestDeliveredTo] [varchar](50) NULL,
	[ArrestDeliveredDate] [varchar](50) NULL,
	[OfficerRank] [varchar](50) NULL,
	[OfficerFirstName] [varchar](50) NULL,
	[OfficerMiddleName] [varchar](50) NULL,
	[OfficerLastName] [varchar](50) NULL,
	[OfficerBadgeNumber] [varchar](50) NULL,
	[OfficerId] [varchar](50) NULL,
	[TrooperUnit] [varchar](50) NULL,
	[Bal08Above] [varchar](50) NULL,
	[DUIRefuse] [varchar](50) NULL,
	[DUILicenseSurrendered] [varchar](50) NULL,
	[DUILicenseRSN] [varchar](50) NULL,
	[DuiEligible] [varchar](50) NULL,
	[DUIEligibleRSN] [varchar](50) NULL,
	[DUIBarOffice] [varchar](50) NULL,
	[Status] [varchar](50) NULL,
	[AggressiveDriverFlag] [varchar](50) NULL,
	[CriminalIndicator] [varchar](50) NULL,
	[FileAmount] [varchar](50) NULL,
	[Filler] [varchar](50) NULL,
	[IssueArrestDate] [varchar](50) NULL,
	[OfficerDeliveryVerification] [varchar](50) NULL,
	[DueDate] [varchar](50) NULL,
	[Motorcycle] [varchar](50) NULL,
	[PassengerVehicle16] [varchar](50) NULL,
	[OfficerReExamFlag] [varchar](50) NULL,
	[DUIViolationUnder18] [varchar](50) NULL,
	[ECitationIndicator] [varchar](50) NULL,
	[NameChange] [varchar](50) NULL,
	[CommercialDL] [varchar](50) NULL,
	[GPSLat] [varchar](50) NULL,
	[GPSLong] [varchar](50) NULL,
	[ViolationSignalRedLight] [varchar](50) NULL,
	[ViolationWorkersPresent] [varchar](50) NULL,
	[ViolationHandHeld] [varchar](50) NULL,
	[ViolationSchoolZone] [varchar](50) NULL,
	[AgencyIdentifier] [varchar](50) NULL,
	[PermanentRegistration] [varchar](50) NULL,
	[SpeedMeasuringDeviceId] [varchar](50) NULL,
	[ComplianceDate] [varchar](50) NULL,
	[DLSeize] [varchar](50) NULL,
	[Business] [varchar](max) NULL,
	[FileLogId] [varchar](50) NULL,
	[ExceptionReason] [varchar](max) NULL,
	[ExceptionFlag] [int] NULL,
	[CaseId] [int] NULL,
	[CaseType] [varchar](50) NULL,
	[RunDate] [date] NULL,
	[CaseNumber] [varchar](50) NULL,
	[Statute] [varchar](100) NULL,
	[Code] [varchar](100) NULL,
	[Jurisdiction] [varchar](100) NULL,
	[JurisdictionNumberOdy] [varchar](20) NULL,
	[DocumentID] [int] NULL,
	[DocumentVersionId] [int] NULL,
	[IssueAgencyNameOdy] [varchar](50) NULL,
	[OfficerPartyID] [varchar](50) NULL,
	[VehicleMakeCode] [varchar](50) NULL,
	[VehicleColorCode] [varchar](50) NULL,
	[Degree] [varchar](50) NULL,
	[OfficerFullName] [varchar](50) NULL,
	[CommercialVehicleCodeOdy] [varchar](50) NULL,
	[HazardousMaterialsOdy] [varchar](50) NULL,
	[AggressiveDriverFlagOdy] [varchar](50) NULL,
	[InjuryOdy] [varchar](50) NULL,
	[SeriousInjuryOdy] [varchar](50) NULL,
	[FatalInjuryOdy] [varchar](50) NULL,
	[ZipCodeOdy] [varchar](50) NULL,
	[JurisdictionCode] [varchar](50) NULL,
	[HeightFeet] [varchar](50) NULL,
	[HeightInches] [varchar](50) NULL,
	[StatuteCodeID] [varchar](50) NULL,
	[CriminalCourtReqOdy] [varchar](50) NULL,
	[OfficerIDOdy] [varchar](50) NULL,
	[NodeID] [varchar](10) NULL,
	[CourtMandatory] [varchar](10) NULL,
	[TrooperUnitOdy] [varchar](10) NULL,
	[EventID] [varchar](20) NULL,
	[CriminalCase] [char](1) NULL,
	[VendorAgencyId] [int] NULL,
	[WorkFlowItemId] [int] NULL,
	[RaceOdy] [varchar](5) NULL,
	[LastApiAttempt] [datetime] NULL,
	[Processed] [bit] NULL,
	[ViolationExpiredDLOdy] [varchar](20) NULL,
	[NotifySA] [bit] NULL,
	[QueueStatus] [int] NULL,
	[ApiStatus] [bit] NULL,
	[Has_Image] [bit] NULL,
 CONSTRAINT [PK_TrafficCitation_Import] PRIMARY KEY NONCLUSTERED 
(
	[CitationNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TrafficCitation_Import] ADD  CONSTRAINT [DF_TrafficCitation_Import_ExceptionFlag]  DEFAULT ((0)) FOR [ExceptionFlag]
GO

ALTER TABLE [dbo].[TrafficCitation_Import] ADD  CONSTRAINT [DF_TrafficCitation_Import_Processed]  DEFAULT ((0)) FOR [Processed]
GO

ALTER TABLE [dbo].[TrafficCitation_Import] ADD  CONSTRAINT [DF__TrafficCi__ApiSt__1995C0A8]  DEFAULT ((0)) FOR [ApiStatus]
GO

ALTER TABLE [dbo].[TrafficCitation_Import] ADD  CONSTRAINT [DF__TrafficCi__Has_I__68BD7F23]  DEFAULT ((0)) FOR [Has_Image]
GO


