//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficCitationImport2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReferenceEntities : DbContext
    {
        public ReferenceEntities()
            : base("name=ReferenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TrafficCitation_AgencyVendorInfo> TrafficCitation_AgencyVendorInfo { get; set; }
        public virtual DbSet<TrafficCitation_ImportFileLog> TrafficCitation_ImportFileLog { get; set; }
        public virtual DbSet<TrafficCitation_Import> TrafficCitation_Import { get; set; }
    
        public virtual int ACID_Reference()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACID_Reference");
        }
    
        public virtual int Application_Add(Nullable<int> applicationID, string applicationName, string applicationType, string schedule, string createdBy)
        {
            var applicationIDParameter = applicationID.HasValue ?
                new ObjectParameter("applicationID", applicationID) :
                new ObjectParameter("applicationID", typeof(int));
    
            var applicationNameParameter = applicationName != null ?
                new ObjectParameter("applicationName", applicationName) :
                new ObjectParameter("applicationName", typeof(string));
    
            var applicationTypeParameter = applicationType != null ?
                new ObjectParameter("applicationType", applicationType) :
                new ObjectParameter("applicationType", typeof(string));
    
            var scheduleParameter = schedule != null ?
                new ObjectParameter("schedule", schedule) :
                new ObjectParameter("schedule", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Application_Add", applicationIDParameter, applicationNameParameter, applicationTypeParameter, scheduleParameter, createdByParameter);
        }
    
        public virtual ObjectResult<ApplicationHealth_GetLatest_Result> ApplicationHealth_GetLatest()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ApplicationHealth_GetLatest_Result>("ApplicationHealth_GetLatest");
        }
    
        public virtual int Citation_LoadTestData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Citation_LoadTestData");
        }
    
        public virtual int Citation_ProcessRules(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Citation_ProcessRules", fileLogIdParameter);
        }
    
        public virtual int Citation_ValidateCitationNumberPresent(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("fileLogId", fileLogId) :
                new ObjectParameter("fileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Citation_ValidateCitationNumberPresent", fileLogIdParameter);
        }
    
        public virtual int Citation_ValidateDriverLicenseState(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("fileLogId", fileLogId) :
                new ObjectParameter("fileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Citation_ValidateDriverLicenseState", fileLogIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CitationImport2_GetLastFileLogId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CitationImport2_GetLastFileLogId");
        }
    
        public virtual ObjectResult<CitationImport2_GetVendorList_Result> CitationImport2_GetVendorList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CitationImport2_GetVendorList_Result>("CitationImport2_GetVendorList");
        }
    
        public virtual int DataForDemo_Process(Nullable<int> batchId)
        {
            var batchIdParameter = batchId.HasValue ?
                new ObjectParameter("batchId", batchId) :
                new ObjectParameter("batchId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DataForDemo_Process", batchIdParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> DLCustomer_Insert(Nullable<System.Guid> batchGuid, string firstName, string middleName, string lastName, string nameSuffix, string raceCode, string genderCode, Nullable<System.DateTime> dateOfBirth, Nullable<bool> isDeceased, Nullable<bool> sharePersonalInfo, Nullable<int> heightInCm)
        {
            var batchGuidParameter = batchGuid.HasValue ?
                new ObjectParameter("batchGuid", batchGuid) :
                new ObjectParameter("batchGuid", typeof(System.Guid));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("middleName", middleName) :
                new ObjectParameter("middleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var nameSuffixParameter = nameSuffix != null ?
                new ObjectParameter("nameSuffix", nameSuffix) :
                new ObjectParameter("nameSuffix", typeof(string));
    
            var raceCodeParameter = raceCode != null ?
                new ObjectParameter("raceCode", raceCode) :
                new ObjectParameter("raceCode", typeof(string));
    
            var genderCodeParameter = genderCode != null ?
                new ObjectParameter("genderCode", genderCode) :
                new ObjectParameter("genderCode", typeof(string));
    
            var dateOfBirthParameter = dateOfBirth.HasValue ?
                new ObjectParameter("dateOfBirth", dateOfBirth) :
                new ObjectParameter("dateOfBirth", typeof(System.DateTime));
    
            var isDeceasedParameter = isDeceased.HasValue ?
                new ObjectParameter("isDeceased", isDeceased) :
                new ObjectParameter("isDeceased", typeof(bool));
    
            var sharePersonalInfoParameter = sharePersonalInfo.HasValue ?
                new ObjectParameter("sharePersonalInfo", sharePersonalInfo) :
                new ObjectParameter("sharePersonalInfo", typeof(bool));
    
            var heightInCmParameter = heightInCm.HasValue ?
                new ObjectParameter("heightInCm", heightInCm) :
                new ObjectParameter("heightInCm", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("DLCustomer_Insert", batchGuidParameter, firstNameParameter, middleNameParameter, lastNameParameter, nameSuffixParameter, raceCodeParameter, genderCodeParameter, dateOfBirthParameter, isDeceasedParameter, sharePersonalInfoParameter, heightInCmParameter);
        }
    
        public virtual ObjectResult<string> DLVendoeResponse_Insert(Nullable<int> requestId, Nullable<System.DateTime> requestDate, Nullable<System.DateTime> weekEndingDate, Nullable<int> resultCount, Nullable<int> mixTransactionId, Nullable<int> timesRequested)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("requestId", requestId) :
                new ObjectParameter("requestId", typeof(int));
    
            var requestDateParameter = requestDate.HasValue ?
                new ObjectParameter("requestDate", requestDate) :
                new ObjectParameter("requestDate", typeof(System.DateTime));
    
            var weekEndingDateParameter = weekEndingDate.HasValue ?
                new ObjectParameter("weekEndingDate", weekEndingDate) :
                new ObjectParameter("weekEndingDate", typeof(System.DateTime));
    
            var resultCountParameter = resultCount.HasValue ?
                new ObjectParameter("resultCount", resultCount) :
                new ObjectParameter("resultCount", typeof(int));
    
            var mixTransactionIdParameter = mixTransactionId.HasValue ?
                new ObjectParameter("mixTransactionId", mixTransactionId) :
                new ObjectParameter("mixTransactionId", typeof(int));
    
            var timesRequestedParameter = timesRequested.HasValue ?
                new ObjectParameter("timesRequested", timesRequested) :
                new ObjectParameter("timesRequested", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DLVendoeResponse_Insert", requestIdParameter, requestDateParameter, weekEndingDateParameter, resultCountParameter, mixTransactionIdParameter, timesRequestedParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> DynamicEmail_EmailToSend_Get(string caseType)
        {
            var caseTypeParameter = caseType != null ?
                new ObjectParameter("caseType", caseType) :
                new ObjectParameter("caseType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DynamicEmail_EmailToSend_Get", caseTypeParameter);
        }
    
        public virtual int DynamicEmail_MetaData_ABCD_Get(Nullable<int> recordId)
        {
            var recordIdParameter = recordId.HasValue ?
                new ObjectParameter("recordId", recordId) :
                new ObjectParameter("recordId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DynamicEmail_MetaData_ABCD_Get", recordIdParameter);
        }
    
        public virtual int DynamicEmail_MetaData_BCDE_Get(Nullable<int> recordId)
        {
            var recordIdParameter = recordId.HasValue ?
                new ObjectParameter("recordId", recordId) :
                new ObjectParameter("recordId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DynamicEmail_MetaData_BCDE_Get", recordIdParameter);
        }
    
        public virtual int DynamicEmail_MetaData_Get(string caseType, Nullable<int> recordId)
        {
            var caseTypeParameter = caseType != null ?
                new ObjectParameter("caseType", caseType) :
                new ObjectParameter("caseType", typeof(string));
    
            var recordIdParameter = recordId.HasValue ?
                new ObjectParameter("recordId", recordId) :
                new ObjectParameter("recordId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DynamicEmail_MetaData_Get", caseTypeParameter, recordIdParameter);
        }
    
        public virtual ObjectResult<DynamicEmail_Template_Get_Result> DynamicEmail_Template_Get(string caseType)
        {
            var caseTypeParameter = caseType != null ?
                new ObjectParameter("caseType", caseType) :
                new ObjectParameter("caseType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DynamicEmail_Template_Get_Result>("DynamicEmail_Template_Get", caseTypeParameter);
        }
    
        public virtual int InsertLog(string application, string level, string callSite, string type, string message, string stackTrace, string innerException, string additionalInfo)
        {
            var applicationParameter = application != null ?
                new ObjectParameter("application", application) :
                new ObjectParameter("application", typeof(string));
    
            var levelParameter = level != null ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(string));
    
            var callSiteParameter = callSite != null ?
                new ObjectParameter("callSite", callSite) :
                new ObjectParameter("callSite", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            var stackTraceParameter = stackTrace != null ?
                new ObjectParameter("stackTrace", stackTrace) :
                new ObjectParameter("stackTrace", typeof(string));
    
            var innerExceptionParameter = innerException != null ?
                new ObjectParameter("innerException", innerException) :
                new ObjectParameter("innerException", typeof(string));
    
            var additionalInfoParameter = additionalInfo != null ?
                new ObjectParameter("additionalInfo", additionalInfo) :
                new ObjectParameter("additionalInfo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertLog", applicationParameter, levelParameter, callSiteParameter, typeParameter, messageParameter, stackTraceParameter, innerExceptionParameter, additionalInfoParameter);
        }
    
        public virtual int InsertLog_WebApi(string application, string level, string callSite, string type, string message, string stackTrace, string innerException, string additionalInfo)
        {
            var applicationParameter = application != null ?
                new ObjectParameter("application", application) :
                new ObjectParameter("application", typeof(string));
    
            var levelParameter = level != null ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(string));
    
            var callSiteParameter = callSite != null ?
                new ObjectParameter("callSite", callSite) :
                new ObjectParameter("callSite", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            var stackTraceParameter = stackTrace != null ?
                new ObjectParameter("stackTrace", stackTrace) :
                new ObjectParameter("stackTrace", typeof(string));
    
            var innerExceptionParameter = innerException != null ?
                new ObjectParameter("innerException", innerException) :
                new ObjectParameter("innerException", typeof(string));
    
            var additionalInfoParameter = additionalInfo != null ?
                new ObjectParameter("additionalInfo", additionalInfo) :
                new ObjectParameter("additionalInfo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertLog_WebApi", applicationParameter, levelParameter, callSiteParameter, typeParameter, messageParameter, stackTraceParameter, innerExceptionParameter, additionalInfoParameter);
        }
    
        public virtual int sp_ApplicationHealth_Update(Nullable<int> applicationID, string applicationState, Nullable<bool> healthStatus, string comment, string createdBy)
        {
            var applicationIDParameter = applicationID.HasValue ?
                new ObjectParameter("applicationID", applicationID) :
                new ObjectParameter("applicationID", typeof(int));
    
            var applicationStateParameter = applicationState != null ?
                new ObjectParameter("applicationState", applicationState) :
                new ObjectParameter("applicationState", typeof(string));
    
            var healthStatusParameter = healthStatus.HasValue ?
                new ObjectParameter("healthStatus", healthStatus) :
                new ObjectParameter("healthStatus", typeof(bool));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ApplicationHealth_Update", applicationIDParameter, applicationStateParameter, healthStatusParameter, commentParameter, createdByParameter);
        }
    
        public virtual ObjectResult<sp_Tags_TestAdd_Result> sp_Tags_TestAdd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Tags_TestAdd_Result>("sp_Tags_TestAdd");
        }
    
        public virtual ObjectResult<sp_Tags_TestDelete_Result> sp_Tags_TestDelete()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Tags_TestDelete_Result>("sp_Tags_TestDelete");
        }
    
        public virtual ObjectResult<sp_Tags_TestUpdate_Result> sp_Tags_TestUpdate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Tags_TestUpdate_Result>("sp_Tags_TestUpdate");
        }
    
        public virtual int sp_TagsBasicAdd(string id, string name)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TagsBasicAdd", idParameter, nameParameter);
        }
    
        public virtual int sp_TagsBasicDelete(string tagId)
        {
            var tagIdParameter = tagId != null ?
                new ObjectParameter("TagId", tagId) :
                new ObjectParameter("TagId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TagsBasicDelete", tagIdParameter);
        }
    
        public virtual int sp_TagsBasicUpdate(string tagId, string tagName)
        {
            var tagIdParameter = tagId != null ?
                new ObjectParameter("TagId", tagId) :
                new ObjectParameter("TagId", typeof(string));
    
            var tagNameParameter = tagName != null ?
                new ObjectParameter("TagName", tagName) :
                new ObjectParameter("TagName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TagsBasicUpdate", tagIdParameter, tagNameParameter);
        }
    
        public virtual int sp_TagsExpandedAdd(string tagId, string tagName)
        {
            var tagIdParameter = tagId != null ?
                new ObjectParameter("TagId", tagId) :
                new ObjectParameter("TagId", typeof(string));
    
            var tagNameParameter = tagName != null ?
                new ObjectParameter("TagName", tagName) :
                new ObjectParameter("TagName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TagsExpandedAdd", tagIdParameter, tagNameParameter);
        }
    
        public virtual int sp_TagsExpandedDelete(string tagId)
        {
            var tagIdParameter = tagId != null ?
                new ObjectParameter("TagId", tagId) :
                new ObjectParameter("TagId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TagsExpandedDelete", tagIdParameter);
        }
    
        public virtual int sp_TagsExpandedUpdate(string tagId, string tagName)
        {
            var tagIdParameter = tagId != null ?
                new ObjectParameter("TagId", tagId) :
                new ObjectParameter("TagId", typeof(string));
    
            var tagNameParameter = tagName != null ?
                new ObjectParameter("TagName", tagName) :
                new ObjectParameter("TagName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TagsExpandedUpdate", tagIdParameter, tagNameParameter);
        }
    
        public virtual int TalentManagement_LoadEmployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TalentManagement_LoadEmployee");
        }
    
        public virtual int TalentManagement_LoadEmployeeHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TalentManagement_LoadEmployeeHistory");
        }
    
        public virtual int TalentManagement_LoadEmployeeStage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TalentManagement_LoadEmployeeStage");
        }
    
        public virtual int TalentManagment_BatchUpdate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TalentManagment_BatchUpdate");
        }
    
        public virtual int TEST_DataForDemo_Test1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TEST_DataForDemo_Test1");
        }
    
        public virtual int TrafficCitationImport_CitationAlreadyExistInOdyssey(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_CitationAlreadyExistInOdyssey", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_FutureBirthDate(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_FutureBirthDate", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_GetTrooperUnit(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_GetTrooperUnit", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_LinkTrooperUnitToFHP(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_LinkTrooperUnitToFHP", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_LookupAgencyName(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_LookupAgencyName", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_MissingBirthDate(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_MissingBirthDate", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_MissingCitationNumber(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_MissingCitationNumber", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_MissingDriverLicense(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_MissingDriverLicense", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_MissingFirstName(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_MissingFirstName", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_MissingGender(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_MissingGender", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_MissingLastName(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_MissingLastName", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_MissingOffesnseDate(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_MissingOffesnseDate", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_MissingOrInvalidRace(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_MissingOrInvalidRace", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_OldOffesnseDate(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_OldOffesnseDate", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_PopulateFHPTrooperUnitOdy(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_PopulateFHPTrooperUnitOdy", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_PopulateOfficerIDOdy(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_PopulateOfficerIDOdy", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_RuleMaster(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_RuleMaster", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_SetFHPAgencyCode(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_SetFHPAgencyCode", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_ValidateBirthDate(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_ValidateBirthDate", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_ValidateDLState(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_ValidateDLState", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_ValidateFHPTroopers(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_ValidateFHPTroopers", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_ImportCitationsToOdyssey(Nullable<int> fileLogId, Nullable<int> vendorAgencyId, string localPath)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            var vendorAgencyIdParameter = vendorAgencyId.HasValue ?
                new ObjectParameter("VendorAgencyId", vendorAgencyId) :
                new ObjectParameter("VendorAgencyId", typeof(int));
    
            var localPathParameter = localPath != null ?
                new ObjectParameter("LocalPath", localPath) :
                new ObjectParameter("LocalPath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_ImportCitationsToOdyssey", fileLogIdParameter, vendorAgencyIdParameter, localPathParameter);
        }
    
        public virtual int TrafficCitationImport_SendFailedToQueue(Nullable<int> queFileLogId, string currExceptionFlag)
        {
            var queFileLogIdParameter = queFileLogId.HasValue ?
                new ObjectParameter("QueFileLogId", queFileLogId) :
                new ObjectParameter("QueFileLogId", typeof(int));
    
            var currExceptionFlagParameter = currExceptionFlag != null ?
                new ObjectParameter("CurrExceptionFlag", currExceptionFlag) :
                new ObjectParameter("CurrExceptionFlag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_SendFailedToQueue", queFileLogIdParameter, currExceptionFlagParameter);
        }
    
        public virtual int TrafficCitationImport_ProcessCitations(Nullable<int> fileLogId, string citationNumber)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            var citationNumberParameter = citationNumber != null ?
                new ObjectParameter("CitationNumber", citationNumber) :
                new ObjectParameter("CitationNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_ProcessCitations", fileLogIdParameter, citationNumberParameter);
        }
    
        public virtual int TrafficCitationImport_QueueCitationsFixedManually(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_QueueCitationsFixedManually", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_UpdateJurisdiction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_UpdateJurisdiction");
        }
    
        public virtual int TrafficCitationImport_MarkFileCompletion(Nullable<int> fileLogId)
        {
            var fileLogIdParameter = fileLogId.HasValue ?
                new ObjectParameter("FileLogId", fileLogId) :
                new ObjectParameter("FileLogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_MarkFileCompletion", fileLogIdParameter);
        }
    
        public virtual int TrafficCitationImport_ProcessFailedCitations(string citationNumber)
        {
            var citationNumberParameter = citationNumber != null ?
                new ObjectParameter("CitationNumber", citationNumber) :
                new ObjectParameter("CitationNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrafficCitationImport_ProcessFailedCitations", citationNumberParameter);
        }
    }
}
