//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficCitationImport2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrafficCitation_ImportFileLog
    {
        public int FileLogId { get; set; }
        public System.DateTime FileDate { get; set; }
        public string FileName { get; set; }
        public Nullable<int> RecordCount { get; set; }
        public Nullable<System.DateTime> ProcessStartTime { get; set; }
        public Nullable<System.DateTime> ProcessEndTime { get; set; }
        public string ProcessStatus { get; set; }
        public Nullable<int> VendorAgencyId { get; set; }
    }
}
